Vehicle:
  description: High-level vehicle data.
  type: branch

Vehicle.Chassis:
  description: All data concerning steering, suspension, wheels, and brakes.
  type: branch

Vehicle.Chassis.SteeringWheel:
  description: Steering wheel signals
  type: branch

Vehicle.Chassis.SteeringWheel.Angle:
  datatype: int16
  description: Steering wheel angle. Positive = degrees to the left. Negative = degrees to the right.
  type: sensor
  unit: degrees

Vehicle.CurrentLocation:
  description: The current latitude and longitude of the vehicle.
  type: branch

Vehicle.CurrentLocation.Latitude:
  datatype: double
  description: Current latitude of vehicle in WGS 84 geodetic coordinates, as measured at the position of GNSS receiver antenna.
  max: 90
  min: -90
  type: sensor
  unit: degrees

Vehicle.CurrentLocation.Longitude:
  datatype: double
  description: Current longitude of vehicle in WGS 84 geodetic coordinates, as measured at the position of GNSS receiver antenna.
  max: 180
  min: -180
  type: sensor
  unit: degrees

Vehicle.Powertrain:
  description: Powertrain data for battery management, etc.
  type: branch

Vehicle.Powertrain.TractionBattery:
  description: Battery Management data.
  type: branch

Vehicle.Powertrain.TractionBattery.NominalVoltage:
  comment: Nominal voltage typically refers to voltage of fully charged battery when delivering rated capacity.
  datatype: uint16
  description: Nominal Voltage of the battery.
  type: attribute
  unit: V

Vehicle.Powertrain.TractionBattery.StateOfCharge:
  description: Information on the state of charge of the vehicle's high voltage battery.
  type: branch

Vehicle.Powertrain.TractionBattery.StateOfCharge.CurrentEnergy:
  comment: Current energy could be calculated as .StateOfCharge.Current * .NetCapacity.
  datatype: float
  description: Physical state of charge of high voltage battery expressed in kWh.
  type: sensor
  unit: kWh

Vehicle.Powertrain.Transmission:
  description: Transmission-specific data, stopping at the drive shafts.
  type: branch

Vehicle.Powertrain.Transmission.CurrentGear:
  datatype: int8
  description: The current gear. 0=Neutral, 1/2/..=Forward, -1/-2/..=Reverse.
  type: sensor

Vehicle.Speed:
  datatype: float
  description: Vehicle speed.
  type: sensor
  unit: km/h

Vehicle.VehicleIdentification:
  description: Attributes that identify a vehicle.
  type: branch

Vehicle.VehicleIdentification.VIN:
  datatype: string
  description: 17-character Vehicle Identification Number (VIN) as defined by ISO 3779.
  type: attribute
